version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-password
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql

volumes:
  db-data:
